Repository 2024-Winter-Bootcamp-Team-G/frontend, pull requests merged in 2025-01, with the labels that each got.

#3 버튼 디자인 생성
  eslint.config.js
  postcss.config.js
  public/vite.svg
  src/App.jsx
  src/assets/react.svg
  src/components/Button.jsx
  src/components/Card.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/styles/index.css
  src/styles/tailwind.css
  tailwind.config.js
Labels: 🎨Design, 🚀 Feat

#5 design: 윈도우 기본창 만들기
  package.json
  src/App.jsx
  src/components/Card.jsx
  src/components/Window.jsx
Labels: 🎨Design

#7 design: 배경화면 생성
  eslint.config.js
  src/App.jsx
  src/assets/start-icon.png
  src/components/Background.jsx
  src/components/Button.jsx
Labels: 🎨Design

#9 refactor: 반응형 수정
  src/App.jsx
  src/components/Background.jsx
  src/components/Button.jsx
  src/components/Window.jsx
Labels: 🧹 Refactor

#12 design: 로그인까지 구현....
  src/App.jsx
  src/assets/login-icon.svg
  src/components/Background.jsx
  src/components/Input.jsx
  src/components/Window.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
Labels: 🎨Design

#14 design: 미니홈피 레이아웃 구현
  src/App.jsx
  src/assets/mini_homp.jpg
  src/components/Homp.jsx
  src/components/Window2.jsx
  src/pages/MiniH.jsx
Labels: 🎨Design

#18 반응형 수정하려고 노력함
  src/components/Background.jsx
  src/components/Button.jsx
  src/components/Input.jsx
  src/components/Window.jsx
Labels: 🧹 Refactor

#19 design: 미니홈피 버튼 및 날짜 추가
  src/App.jsx
  src/assets/triangle.svg
  src/components/Mbutton.jsx
  src/components/Window2.jsx
  src/pages/MiniH.jsx
  src/pages/TestPage.jsx
Labels: 🎨Design

#22 design: 미니홈피 레이아웃 반응형
  src/assets/page.svg
  src/components/Mbutton.jsx
  src/components/MiniHomp.jsx
  src/pages/MiniH.jsx
Labels: 🎨Design

#23 design: 미니홈피 팝업창 구현
  src/App.jsx
  src/assets/youtube_icon.png
  src/components/Input.jsx
  src/components/Mpopup.jsx
  src/components/Window.jsx
  src/pages/TestPage.jsx
  src/styles/scrollbar.css
Labels: 🎨Design

#26 Design: 미니홈피 홈 화면 제작
  src/App.jsx
  src/assets/board-help.svg
  src/assets/login-help.svg
  src/assets/sub-help.svg
  src/components/MiniHomp.jsx
  src/components/Mpopup.jsx
  src/pages/Board.jsx
  src/pages/Home.jsx
  src/pages/MiniH.jsx
  src/pages/Notice.jsx
Labels: 🎨Design

#28 feat: 버튼&팝업창 연결
  src/components/MiniHomp.jsx
  src/components/Mpopup.jsx
Labels: 🚀 Feat

#30 design: 마우스 커서 변경
  src/App.jsx
  src/assets/cursor.svg
  src/assets/pointer.svg
  src/styles/cursor.css
Labels: 🎨Design

#34 design: 디테일 수정
  src/assets/mini_homp.jpg
  src/components/Loading.jsx
  src/components/Mbutton.jsx
  src/components/MiniHomp.jsx
  src/components/Mpopup.jsx
Labels: 🎨Design, 🚀 Feat

#36 design: 디테일 수정
  src/App.jsx
  src/components/MiniHomp.jsx
  src/pages/Board.jsx
  src/pages/MiniH.jsx
  src/pages/Notice.jsx
Labels: 🎨Design

#38 design: 보드판 수정
  src/assets/retry.png
  src/components/Mbutton.jsx
  src/components/MiniHomp.jsx
  src/pages/Board.jsx
  src/pages/MiniH.jsx
Labels: 🎨Design

#39 feat: 디테일 수정
  src/components/Mbutton.jsx
  src/components/Mpopup.jsx
  src/components/Window.jsx
  src/components/Window2.jsx
  src/pages/Home.jsx
Labels: 🚀 Feat

#42 보드판 최최최종 수정...
  src/components/Mbutton.jsx
  src/components/MiniHomp.jsx
  src/components/Window2.jsx
  src/pages/Board.jsx
Labels: 🎨Design

#44 design: 알고리즘 분석판 레이아웃
  src/App.jsx
  src/assets/algo.png
  src/components/Background.jsx
  src/pages/Share.jsx
Labels: 🎨Design

#46 design: 스크롤바 숨김&이미지 비율 조정
  package.json
  src/components/Window2.jsx
  src/pages/Board.jsx
  src/pages/MiniH.jsx
  src/pages/Start.jsx
  tailwind.config.js
  yarn.lock
Labels: 🎨Design

#47 design: radar 차트 구현
  package.json
  src/components/RadarChartComponent.jsx
  src/pages/Share.jsx
  yarn.lock
Labels: 🎨Design

#49 design: 벤다이어그램 생성
  src/components/Background.jsx
  src/components/VennDiagram.jsx
  src/pages/Share.jsx
Labels: 🎨Design

#53 design: 알고리즘 보드판 선택창
  src/assets/select.png
  src/components/Select.jsx
  src/pages/MiniH.jsx
  src/pages/Share.jsx
Labels: 🎨Design

#56 feat: 로그인 API 연동
  package.json
  src/App.jsx
  src/pages/Login.jsx
  vite.config.js
  yarn.lock
Labels: 🚀 Feat

#58 feat: 회원가입 api 구현
  src/pages/SignUp.jsx
  vite.config.js
Labels: 🚀 Feat

#61 feat: 로그인 연동 수정
  src/pages/Login.jsx
Labels: 🚀 Feat

#62 chore: cookie.js 정의
  .gitignore
  package.json
  src/api/axios_config.js
  src/utils/cookie.js
  yarn.lock
Labels: 🧭 Chore

#65 Feat/#57 로그아웃 연동
  .gitignore
  package.json
  src/components/Background.jsx
  src/pages/Login.jsx
  yarn.lock
Labels: 🚀 Feat

#63 feat: google oauth 인증 요청 추가
  src/components/Mpopup.jsx
Labels: 🚀 Feat

#66 feat: axios_config 생성
  src/api/axios_config.js
  src/utils/cookie.js
Labels: 🚀 Feat

#68 feat: 로그인, 로그아웃 api 연동 수정
  src/components/Background.jsx
  src/pages/Login.jsx
Labels: 🚀 Feat

#70 refactor: 회원가입 페이지 리팩토링
  src/pages/SignUp.jsx
Labels: 🧹 Refactor

#73 design: 홈피 아이콘 수정 및 기능 추가
  src/assets/homp_icon.png
  src/assets/start_img.png
  src/components/Background.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Start.jsx
Labels: 🎨Design

#77 feat:(임시)보드 생성하기 연동
  src/components/MiniHomp.jsx
  src/pages/Board.jsx
  src/pages/Login.jsx
Labels: 🚀 Feat

#79 feat: 보드 공유하기 api 구현
  src/api/axios_config.js
  src/components/MiniHomp.jsx
  src/components/Mpopup.jsx
  src/pages/Board.jsx
Labels: 🚀 Feat

#81 feat: 게시판 구현
  src/components/MiniHomp.jsx
  src/pages/Board.jsx
  src/pages/MiniH.jsx
  src/pages/Notice.jsx
Labels: 🚀 Feat

#84 feat: 닉네임과 정보수정 연동
  src/components/MiniHomp.jsx
  src/components/Mpopup.jsx
  src/pages/MiniH.jsx
Labels: 🚀 Feat

#85 refactor: 정보수정창 수정
  src/components/Mpopup.jsx
Labels: 🧹 Refactor

#87 refactor: 재생성 이미지 버튼 바꿈/ custom api 추가
  src/App.jsx
  src/api/board.js
  src/components/MiniHomp.jsx
  src/components/Mpopup.jsx
  src/pages/Board.jsx
  src/pages/Notice.jsx
Labels: 🧹 Refactor

#90 feat: 알고리즘 일치율 차트 연동 및 선택창 수정
  src/components/MiniHomp.jsx
  src/components/Mpopup.jsx
  src/components/RadarChartComponent.jsx
  src/components/Select.jsx
  src/components/VennDiagram.jsx
  src/pages/Share.jsx
Labels: 🚀 Feat

#91 feat: 구독 채널 선택 & 보드판 생성 & 게시판 글 누르면 해당 보드판으로 이동
  src/components/MiniHomp.jsx
  src/components/Mpopup.jsx
  src/pages/Board.jsx
  src/pages/Notice.jsx
  src/utils/cookie.js
Labels: 🚀 Feat

#96 feat: 유효코드 공유하기 창 연동하기
  src/components/Match.jsx
  src/components/Mpopup.jsx
  src/pages/Share.jsx
Labels: 🚀 Feat

#98 feat: 보드판 50% 연동
  src/api/board.js
  src/components/Mbutton.jsx
  src/components/MiniHomp.jsx
  src/components/Select.jsx
  src/pages/Board.jsx
  src/pages/MiniH.jsx
  src/pages/Notice.jsx
  src/styles/cursor.css
Labels: 🚀 Feat

#100 feat: 스크린샷 기능 추가, 디자인 부분 수정
  package.json
  src/assets/end-icon.png
  src/components/Background.jsx
  src/components/MiniHomp.jsx
  src/pages/Board.jsx
  src/pages/MiniH.jsx
  yarn.lock
Labels: 🚀 Feat

#102 feat: 알고리즘 일치율 최종
  src/components/Match.jsx
  src/components/RadarChartComponent.jsx
  src/components/Select.jsx
  src/components/VennDiagram.jsx
  src/pages/Share.jsx
  src/pages/SignUp.jsx
Labels: 🚀 Feat

#103 feat: 재생성 api 구현 / 이미지 로딩창 필요...할 듯...
  src/api/board.js
  src/pages/Board.jsx
Labels: 🚀 Feat

#112 design: 홈화면 디자인 수정
  src/assets/boardhome.png
  src/pages/MiniH.jsx
Labels: 🎨Design

#110 feat: 재생성 로딩 추가
  src/pages/Board.jsx
  src/styles/index.css
  tailwind.config.js
Labels: 🚀 Feat

#115 Refactor:일치율 보드판 찐 최종!!
  src/components/RadarChartComponent.jsx
  src/pages/Share.jsx
Labels: 🧹 Refactor

#116 design: 디자인 수정
  src/components/Mbutton.jsx
  src/components/MiniHomp.jsx
  src/pages/Board.jsx
Labels: 🎨Design

#118 design: 일치율 설명문구 수정
  src/pages/Share.jsx
Labels: 🎨Design

#120 [feat] vercel.json 추가
  src/pages/Board.jsx
  vercel.json
Labels: 🚀 Feat

#121 Revert "[feat] vercel.json 추가"
  src/pages/Board.jsx
  vercel.json
Labels: 🏷 Fix

#123 [feat] vercel.json 설정
  vercel.json
Labels: 🚀 Feat

#125 design: 버튼 크기 수정/ 테스트 페이지 삭제
  src/App.jsx
  src/components/Button.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
  src/pages/TestPage.jsx
Labels: 🎨Design

#127 design: 프로필 디자인 수정
  src/assets/NameCat.gif
  src/assets/cat.gif.gif
  src/components/MiniHomp.jsx
  vercel.json
Labels: 🎨Design

#130 design: 홈화면 공지 수정
  src/assets/boardhome.png
  src/pages/MiniH.jsx
Labels: 🎨Design

#134 design: 파비콘, 제목 추가
  favicon.ico
  src/App.jsx
  src/main.jsx
Labels: 🎨Design

#132 design: 팝업창 내용 수정
  src/components/Background.jsx
  src/components/MiniHomp.jsx
  src/pages/MiniH.jsx
  src/pages/SignUp.jsx
Labels: 🎨Design
